pipeline{
    agent any
    stages {
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/cprime-talent/devops-execise-azure--mohan612.git'
            }
        }
        stage('Terraform version'){
             steps{
                 sh 'terraform --version'
             }
        }
        stage('Terraform init'){
             steps{
                 dir('iac') {
                      sh 'terraform init'
                   }
             }
        }
        stage('Terraform validate'){
             steps{
                 dir('iac') {
                      sh 'terraform validate'
                   }
             }
        }
        stage('Terraform plan'){
             steps{
                 dir('iac') {
                      sh 'terraform plan'
                   }
             }
        }
        stage('Terraform apply'){
             steps{
                 dir('iac') {
                      sh 'terraform apply --auto-approve'
                   }
             }
        }
    }
}